version: "3.8"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
      - './client:/usr/src/app'
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    networks:
      - appNet

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - appNet

  server:
    build:
      context: ./server
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '8000:8000'
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - appNet

networks:
  appNet:
    driver: bridge
