tags:
  - name: users
    description: users API
  - name: boost
    description: startup boost API

paths:
  # [GET] users
  /users:
    get:
      tags:
        - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    # [POST] users
    post:
      tags:
        - users
      summary: Add User
      parameters:
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] users/id
  /users/{id}:
    get:
      tags:
        - users
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] users/id
    put:
      tags:
        - users
      summary: Update User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
          type: integer
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] users/id
    delete:
      tags:
        - users
      summary: Delete User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] boost
  /boost:
    get:
      tags:
        - boost
      summary: get all stages with tasks
      responses:
        200:
          descirption: 'OK'

    # [PUT] boost
    put:
      tags:
        - boost
      summary: 'update task within stage'
      parameters:
        - name: stageId
          in: query
          description: stage Id
          required: true
          type: integer
        - name: taskId
          in: query
          description: task id
          required: true
        - name: body
          in: body
          description: update data
          required: true
          schema:
            $ref: '#/definitions/updateBoost'


# definitions
definitions:
  users:
    type: object
    required:
      - email
      - password
    properties:
      id:
        type: integer
        description: user Id
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password
  updateBoost:
    type: object
    required:
      - isChecked
    properties:
      isChecked:
        type: boolean
        description: task is done / not done


schemes:
  - https
  - http
